# Generated by Django 6.0.5 on 2026-05-31 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id_suscripcion', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('duo', 'Duo'), ('familiar', 'Familiar'), ('free', 'Free'), ('premium', 'Premium')], default='free', max_length=10)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=10)),
                ('usuario', models.ForeignKey(db_column='Usuario_id_usuario', on_delete=django.db.models.deletion.PROTECT, to='user.usuario')),
            ],
            options={
                'db_table': 'Suscripción',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.IntegerField(primary_key=True, serialize=False)),
                ('monto', models.FloatField()),
                ('fecha', models.DateTimeField()),
                ('estado', models.CharField(choices=[('cancelado', 'Cancelado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=15)),
                ('suscripcion', models.ForeignKey(blank=True, db_column='Suscripción_id_suscripcion', null=True, on_delete=django.db.models.deletion.PROTECT, to='finanzas.suscripcion')),
            ],
            options={
                'db_table': 'Pago',
            },
        ),
    ]
