# Generated by Django 6.0.5 on 2026-05-30 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voidsound', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('tipo_usuario', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': '[Usuarios].[Usuario]',
            },
        ),
        migrations.CreateModel(
            name='CancionPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancion', models.ForeignKey(db_column='Cancion_id_cancion', on_delete=django.db.models.deletion.CASCADE, to='voidsound.cancion')),
            ],
            options={
                'db_table': '[Usuarios].[CancionPlaylist]',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id_playlist', models.IntegerField(primary_key=True, serialize=False)),
                ('nombrePlaylist', models.CharField(max_length=100)),
                ('canciones', models.ManyToManyField(through='user.CancionPlaylist', to='voidsound.cancion')),
                ('usuario', models.ForeignKey(db_column='Usuario_id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.usuario')),
            ],
            options={
                'db_table': '[Usuarios].[Playlist]',
            },
        ),
        migrations.AddField(
            model_name='cancionplaylist',
            name='playlist',
            field=models.ForeignKey(db_column='Playlist_id_playlist', on_delete=django.db.models.deletion.CASCADE, to='user.playlist'),
        ),
        migrations.CreateModel(
            name='Reproduccion',
            fields=[
                ('id_reproduccion', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('cancion', models.ForeignKey(db_column='Cancion_id_cancion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='voidsound.cancion')),
                ('usuario', models.ForeignKey(db_column='Usuario_id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.usuario')),
            ],
            options={
                'db_table': '[Usuarios].[Reproduccion]',
            },
        ),
        migrations.AlterUniqueTogether(
            name='cancionplaylist',
            unique_together={('playlist', 'cancion')},
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancion', models.ForeignKey(db_column='Cancion_id_cancion', on_delete=django.db.models.deletion.CASCADE, to='voidsound.cancion')),
                ('usuario', models.ForeignKey(db_column='Usuario_id_usuario', on_delete=django.db.models.deletion.CASCADE, to='user.usuario')),
            ],
            options={
                'db_table': '[Usuarios].[Likes]',
                'unique_together': {('usuario', 'cancion')},
            },
        ),
    ]
