# Generated by Django 6.0.5 on 2026-05-29 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id_artista', models.IntegerField(help_text='Id único de cada artista', primary_key=True, serialize=False)),
                ('nombreArtista', models.CharField(help_text='Nombre registrado del artista', max_length=50)),
                ('paisArtista', models.CharField(help_text='País de origen del artista', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreGenero', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id_album', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreAlbum', models.CharField(max_length=100)),
                ('fecha_lanzamiento', models.DateField()),
                ('artista', models.ForeignKey(blank=True, db_column='Artista_id_artista', null=True, on_delete=django.db.models.deletion.PROTECT, to='voidsound.artista')),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id_cancion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreCancion', models.CharField(max_length=100)),
                ('duracion', models.IntegerField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=10)),
                ('album', models.ForeignKey(db_column='Album_id_album', on_delete=django.db.models.deletion.PROTECT, to='voidsound.album')),
                ('genero', models.ForeignKey(db_column='Genero_id_genero', on_delete=django.db.models.deletion.PROTECT, to='voidsound.genero')),
            ],
        ),
    ]
