# Generated by Django 6.0.5 on 2026-05-30 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voidsound', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table='[Contenido].[Album]',
        ),
        migrations.AlterModelTable(
            name='artista',
            table='[Contenido].[Artista]',
        ),
        migrations.AlterModelTable(
            name='cancion',
            table='[Contenido].[Cancion]',
        ),
        migrations.AlterModelTable(
            name='genero',
            table='[Contenido].[Genero]',
        ),
    ]
